package com.sriram.ecommerce.product.model;
// Generated 12-Jun-2025, 7:42:13 am by Hibernate Tools 4.0.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.springframework.boot.autoconfigure.web.WebProperties;

/**
 * Colour generated by hbm2java
 */
@Entity
@Table(name="colour"
    ,schema="public"
)
public class Colour implements java.io.Serializable {


     private int colourId;
     private String colourName;

    public Colour() {
    }

    public Colour(int colourId, String colourName) {
       this.colourId = colourId;
       this.colourName = colourName;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="colour_id", unique=true, nullable=false)
    public int getColourId() {
        return this.colourId;
    }
    
    public void setColourId(int colourId) {
        this.colourId = colourId;
    }

    
    @Column(name="colour_name", nullable=false, length=100)
    public String getColourName() {
        return this.colourName;
    }
    
    public void setColourName(String colourName) {
        this.colourName = colourName;
    }




}


