package com.sriram.ecommerce.product.model;
// Generated 12-Jun-2025, 7:42:13 am by Hibernate Tools 4.0.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Colour generated by hbm2java
 */
@Entity
@Table(name="color"
    ,schema="public"
)
public class Color implements java.io.Serializable {


     private int colourId;
     private String colorName;
     private String colorCode;
     private Product product;



   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="color_id", unique=true, nullable=false)
    public int getColorId() {
        return this.colourId;
    }
    
    public void setColorId(int colourId) {
        this.colourId = colourId;
    }

    
    @Column(name="color_name", nullable=false, length=100)
    public String getColorName() {
        return this.colorName;
    }
    
    public void setColorName(String colorName) {
        this.colorName = colorName;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id")
    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }
    @Column(name = "color_code",nullable = false,length = 100)
    public String getColorCode() {
        return colorCode;
    }

    public void setColorCode(String colorCode) {
        this.colorCode = colorCode;
    }
}


