package com.sriram.ecommerce.product.model;// default package
// Generated 10-Dec-2025, 4:01:25 pm by Hibernate Tools 6.2.24.Final


import com.sriram.ecommerce.product.domain.ParentSubCategoryDomain;
import jakarta.persistence.Column;
import jakarta.persistence.ColumnResult;
import jakarta.persistence.ConstructorResult;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.NamedNativeQuery;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SqlResultSetMapping;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import org.springframework.data.jpa.repository.Query;

import java.sql.Date;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;

/**
 * ParentCategory generated by hbm2java
 */
@Entity
@Table(name="parent_category"
    ,schema="public"
)
@NamedNativeQuery(
        name = "ParentCategory.fetchParentWithSubCategories",
        query =("""
                select p.parent_category_id as parentCategoryId,
                p.category_name as parentCategoryName,
                sc.sub_category_id as subCategoryId ,
                sc.category_name as subCategoryName
                from parent_category p
                 join sub_category sc
                on  p.parent_category_id=sc.parent_category_id
                """),
          resultSetMapping = "ParentSubCategoryMapping"
)
@SqlResultSetMapping(
        name = "ParentSubCategoryMapping",
        classes = @ConstructorResult(
                targetClass = ParentSubCategoryDomain.class,
                columns = {
                        @ColumnResult(name = "parentCategoryId", type = Integer.class),
                        @ColumnResult(name = "parentCategoryName", type = String.class),
                        @ColumnResult(name = "subCategoryId", type = Integer.class),
                        @ColumnResult(name = "subCategoryName", type = String.class)
                }
        )
)
public class ParentCategory implements java.io.Serializable {


     private int parentCategoryId;
     private String categoryName;
     private LocalDate createdDate;
     private LocalDate updatedDate;
     private Set<SubCategory> subCategories = new HashSet(0);

    public ParentCategory() {
    }

	
    public ParentCategory(int parentCategoryId, String categoryName) {
        this.parentCategoryId = parentCategoryId;
        this.categoryName = categoryName;
    }
    public ParentCategory(int parentCategoryId, String categoryName, LocalDate createdDate, LocalDate updatedDate, Set subCategories) {
       this.parentCategoryId = parentCategoryId;
       this.categoryName = categoryName;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
       this.subCategories = subCategories;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="parent_category_id", unique=true, nullable=false)
    public int getParentCategoryId() {
        return this.parentCategoryId;
    }
    
    public void setParentCategoryId(int parentCategoryId) {
        this.parentCategoryId = parentCategoryId;
    }

    
    @Column(name="category_name", nullable=false, length=50)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }


    @Column(name="created_date", length=13)
    public LocalDate getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(LocalDate createdDate) {
        this.createdDate = createdDate;
    }


    @Column(name="updated_date", length=13)
    public LocalDate getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(LocalDate updatedDate) {
        this.updatedDate = updatedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="parentCategory")
    public Set<SubCategory> getSubCategories() {
        return this.subCategories;
    }
    
    public void setSubCategories(Set<SubCategory> subCategories) {
        this.subCategories = subCategories;
    }




}


