package com.sriram.ecommerce.product.model;// default package
// Generated 19-Dec-2025, 5:24:57 pm by Hibernate Tools 6.2.24.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * ProductVariant generated by hbm2java
 */
@Entity
@Table(name = "product_variant"
        , schema = "public"
        , uniqueConstraints = @UniqueConstraint(columnNames = {"product_id", "color_id"})
)
public class ProductVariant implements java.io.Serializable {


    private int variantId;
    private Color color;
    private Product product;
    private BigDecimal price;
    private Integer stock;
    private List<ProductImage> productImages ;


    @Id
    @Column(name = "variant_id", unique = true, nullable = false)
    public int getVariantId() {
        return this.variantId;
    }

    public void setVariantId(int variantId) {
        this.variantId = variantId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "color_id", nullable = false)
    public Color getColor() {
        return this.color;
    }

    public void setColor(Color color) {
        this.color = color;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }


    @Column(name = "price", precision = 10, scale = 2)
    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }


    @Column(name = "stock")
    public Integer getStock() {
        return this.stock;
    }

    public void setStock(Integer stock) {
        this.stock = stock;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "productVariant")
    public List<ProductImage> getProductImages() {
        return this.productImages;
    }

    public void setProductImages(List<ProductImage> productImages) {
        this.productImages = productImages;
    }


}


