package com.sriram.ecommerce.product.model;
// Generated 31-May-2025, 5:05:44 pm by Hibernate Tools 4.0.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,schema="public"
)
public class Product implements java.io.Serializable {

     private int productId;
     private Brand brand;
     private String productName;
     private String description;
     private Double unitPrice;
     private Integer quantity;
     private LocalDateTime createdDate;
     private LocalDateTime updateDate;
     private Set<Inventory> inventories = new HashSet<Inventory>(0);
     private Set<Discount> discounts = new HashSet<Discount>(0);
     private Set<Color> colors=new HashSet<>(0);


     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="product_id", unique=true, nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }



@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="brand_id")
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }

    
    @Column(name="product_name", nullable=false, length=200)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name="price", nullable=false, precision=10, scale=0)
    public Double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    @Column(name="quantity")
    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false, length=29)
    public LocalDateTime getcreatedDate() {
        return this.createdDate;
    }
    
    public void setcreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=29)
    public LocalDateTime getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(LocalDateTime upLocalDateTimeLocalDateTime) {
        this.updateDate = upLocalDateTimeLocalDateTime;
    }


   @OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Inventory> getInventories() {
        return this.inventories;
    }
    
    public void setInventories(Set<Inventory> inventories) {
        this.inventories = inventories;
    }

   @OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Discount> getDiscounts() {
        return this.discounts;
    }
    
    public void setDiscounts(Set<Discount> discounts) {
        this.discounts = discounts;
    }
    @OneToMany(fetch = FetchType.LAZY,mappedBy = "product")
    public Set<Color> getColours() {
        return colors;
    }

    public void setColours(Set<Color> colors) {
        this.colors = colors;
    }



}


