package com.sriram.ecommerce.product.model;// default package
// Generated 10-Dec-2025, 4:01:25 pm by Hibernate Tools 6.2.24.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

import java.sql.Date;

/**
 * SubCategory generated by hbm2java
 */
@Entity
@Table(name="sub_category"
    ,schema="public"
)
public class SubCategory implements java.io.Serializable {


     private int subCategoryId;
     private ParentCategory parentCategory;
     private String categoryName;
     private Date createDate;
     private Date updatedDate;

    public SubCategory() {
    }

	
    public SubCategory(int subCategoryId, String categoryName) {
        this.subCategoryId = subCategoryId;
        this.categoryName = categoryName;
    }
    public SubCategory(int subCategoryId, ParentCategory parentCategory, String categoryName, Date createDate, Date updatedDate) {
       this.subCategoryId = subCategoryId;
       this.parentCategory = parentCategory;
       this.categoryName = categoryName;
       this.createDate = createDate;
       this.updatedDate = updatedDate;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="sub_category_id", unique=true, nullable=false)
    public int getSubCategoryId() {
        return this.subCategoryId;
    }
    
    public void setSubCategoryId(int subCategoryId) {
        this.subCategoryId = subCategoryId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent_category_id")
    public ParentCategory getParentCategory() {
        return this.parentCategory;
    }
    
    public void setParentCategory(ParentCategory parentCategory) {
        this.parentCategory = parentCategory;
    }

    
    @Column(name="category_name", nullable=false, length=50)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="create_date", length=13)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_date", length=13)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


